name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef
    - name: Build with dotnet
      run: dotnet build --configuration Release NextGen.sln

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: dotnet test NextGen.sln --configuration Release --filter TestCategory=UnitTests

  integration-tests:
    runs-on: ubuntu-latest
    services:
      sql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: dotnet test NextGen.sln --configuration Release --filter TestCategory=IntegrationTests
      env:
        ConnectionStrings__DefaultConnection: Server=.;Database=NextGenTestDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true